server {
  listen 8080;
  server_name _;
  root /usr/share/nginx/html;
  add_header Accept-Ranges "bytes" always;
  add_header Access-Control-Allow-Origin "http://localhost:4173" always;
  add_header Access-Control-Allow-Methods "GET, HEAD, OPTIONS" always;
  add_header Access-Control-Allow-Headers "Origin, Range" always;
  add_header Access-Control-Expose-Headers "Accept-Ranges, Content-Range, Content-Length, ETag" always;
  add_header Timing-Allow-Origin "http://localhost:4173" always;

  location / {
    if ($request_method = OPTIONS) { return 204; }
  }
}
